name: e2e
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/actions/virtual-environments/issues/710
      - name: Add emoji font 🤩
        run: sudo apt-get install fonts-noto-color-emoji -y

      # install NPM dependencies and Cypress
      # https://github.com/cypress-io/github-action
      - name: Install 📦
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      # start the local server and Expo project
      - name: Start the app 🚦
        run: npm run web:server &

      # run Cypress tests with Percy
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          command-prefix: 'percy exec -- npx'
          wait-on: 'http://localhost:19006'
        # inject the Percy token
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
