name: e2e
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # install NPM dependencies and Cypress
      # https://github.com/cypress-io/github-action
      - name: Install 📦
        uses: cypress-io/github-action@v3
        with:
          runTests: false

      # start the local server and Expo project
      - name: Start the app 🚦
        run: npm run web:server &

      # run Cypress tests with Percy
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          install: false
          command-prefix: 'percy exec -- npx'
          wait-on: 'http://localhost:19006'
          record: true
          group: all
        # inject the Percy token
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
